{% set name = "channels" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9e707487431ba5dbce9af982970dab3b0efd786580fadb99e45dca5e39fdd59

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - asgiref >=3.6.0,<4
    - daphne >=4.0.0
    - django >=4.2
    - python >=3.8

test:
  imports:
    - channels
    - channels.generic
    - channels.management
    - channels.management.commands
    - channels.security
    - channels.testing

about:
  home: http://github.com/django/channels
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Brings async, event-driven capabilities to Django. Django 4.2 and up only.
  doc_url: https://channels.readthedocs.io
  dev_url: http://github.com/django/channels

extra:
  recipe-maintainers:
    - chrisbarber
    - swainn
