{% set name = "channels" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0ed375719f5c1851861f05ed4ce78b0166f9245ca0ecd836cb77d4bb531489d

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - asgiref >=3.6.0,<4
    - daphne >=4.0.0
    - django >=4.2
    - python >=3.8

test:
  imports:
    - channels
    - channels.generic
    - channels.management
    - channels.management.commands
    - channels.security
    - channels.testing

about:
  home: http://github.com/django/channels
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Brings async, event-driven capabilities to Django. Django 4.2 and up only.
  doc_url: https://channels.readthedocs.io
  dev_url: http://github.com/django/channels

extra:
  recipe-maintainers:
    - chrisbarber
    - swainn
